import Head from "next/head"
import Banner from "../components/banner/Banner"
import Header from "../components/header/Header"

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-commerce Product Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Banner />
    </div>
  )
}
